/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_seven_file_FileEncrypt */

#ifndef _Included_com_seven_file_FileEncrypt
#define _Included_com_seven_file_FileEncrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seven_file_FileEncrypt
 * Method:    encypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_seven_file_FileEncrypt_encypt
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_seven_file_FileEncrypt
 * Method:    deEncrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_seven_file_FileEncrypt_deEncrypt
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
